### ISSUE TITLE
Making as not-provider

### ISSUE THREAD

**Issue by mnabialek** [felixkiss/uniquewith-validator#21]
As Laravel supports registering only one validator service provider, it would be nice if this plugin uses extend method to register validator:

```
Validator::extend('unique_with', '\Felixkiss\UniqueWithValidator\ValidatorExtension@validateUniqueWith');
```

Now it obviously won't work.

At the moment if we use this validator, we cannot register any validator service provider and if someone else used this method using service provider it will be impossible to use those 2 validators

**Comment by ziming** [comment]
Hmm strange currently I have 3 validation service provider, 2 of them works except uniquewith-validator. Hope I can be enlightened as to what is going on here.

```
'Propaganistas\LaravelPhone\LaravelPhoneServiceProvider',
'Felixkiss\UniqueWithValidator\UniqueWithValidatorServiceProvider',
'Intervention\Validation\ValidationServiceProvider',
```
