### ISSUE TITLE
L5.1 - Validation always passes

### ISSUE THREAD

**Issue by macmotp** [felixkiss/uniquewith-validator#35]
I was using your functionality and it worked perfectly but after a recent update I noticed that the unique_with validation is always returning me "true". I'm sorry I cannot be more specific on my code, but I can assure you I was using it correctly as your guide says.

**Comment by felixkiss** [comment]
It works for me perfectly. I can't help if I have nothing to work with.

If you can't be more specific with your code, please rollback `uniquewith-validation` to an earlier version and tell what version change made it work again.

**Comment by lbausch** [comment]
I'm experiencing the same issue. Tried all 2.* versions of uniquewith-validator and some older 5.1.* versions of Laravel. The issue occured every time.

My validation rule looks like this: `'name' => 'required|unique_with:table,owner_id'`. The table requires the combination of "name" and "owner_id" to be unique.

The executed validation query checks for `where `name` = ? and `owner_id` is null`. Because `owner_id` is not present in the input it is set to null (by calling `array_get` in line 84 in `ValidatorExtension.php`).
Of course this statement always returns 0 rows and makes the validator returning true.
I'm not having "owner_id" in the input because the value is later set manually with the ID of the current authenticated user.

Any idea to fix this, besides modifying the input before passing it to validation?

**Comment by felixkiss** [comment]
@lbausch You have to pass all values involved to the validator. That is the whole point of it. No workaround possible.

**Comment by lbausch** [comment]
@felixkiss Thank you for your reply - thats what I supposed already. Do you have any best practice for modifying the input in Form Requests?

**Comment by webcrazy** [comment]
Yeah... I've test with normal validation from controller which is not from Form Request. From Form request, it doesn't work which means it always return true. Any idea? My laravel version is 5.1.

bty I love ur package. @felixkiss .

**Comment by felixkiss** [comment]
@lbausch 

Something like this:

```php
<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;
use Symfony\Component\HttpFoundation\Request as SymfonyRequest;

class FooRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        $this->request->set('user_id', Auth::user()->id);
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'test' => 'required',
        ];
    }
}
```

Not ideal to set it in the `authorize` method, but it didn't work in the constructor and I know that `authorize` will be called at least once. You might find a better method to override and set your custom data.

---

@webcrazy 

Please post the relevant parts of your code (form request including rules and data you are trying to validate).

**Comment by webcrazy** [comment]
Hi @felixkiss ...

here is mine.

```
// this one works.
public function store(Request $request)
    {
        $rules = array(
            'car_type_id' => 'required|unique_with:cars,brand_id,model_year',
            'brand_id' => 'required|integer',
            'hscode' => 'required|numeric',
            'model_year' => 'required|digits:4',
            'engine_power' => 'required',
        );

        $validator = Validator::make($request->all(), $rules);

        if($validator->fails())
        {
            return Redirect::back()->withErrors($validator)->withInput();
        }

        Car::create($request->all());
        return redirect()->route('cars.index');
    }



// this one doesn't work.

   // Controller
    public function store(CreateCarRequest $request)
    {
        Car::create($request->all());
        return redirect()->route('cars.index');
    }

   // rules from Form Request.
    public function rules()
    {
        return [
            'brand_id' => 'required|unique_with:cars,car_type_id,brand_id,model_year',
            'car_type_id' => 'required|integer',
            'brand_id' => 'required|integer',
            'hscode' => 'required|numeric',
            'model_year' => 'required|digits:4',
            'engine_power' => 'required',
        ];
    }
```

**Comment by felixkiss** [comment]
@webcrazy Are you overriding the `messages` method in either `CreateCarRequest` or `App\Http\Requests\Request`?

**Comment by webcrazy** [comment]
@felixkiss Ops...terribly yes. Now working. Thanks
