### ISSUE TITLE
validation message in lang

### ISSUE THREAD

**Issue by ReemAliT** [felixkiss/uniquewith-validator#36]
the validation is working fine but I get validation error as 
" uniquewith-validator::validation.unique_with"

I set
"unique_with" => 'This combination of :fields already exists.',in validation file 
but doesn't appear at all

**Comment by felixkiss** [comment]
Please refer to http://laravel.com/docs/5.1/localization#overriding-vendor-language-files

**Comment by ReemAliT** [comment]
@felixkiss  I set 

\resources\lang\vendor\felixkiss\uniquewith-validator\ar\validation.php

but get the same .. is it right to add vendor and the path as above , or it's about validation.php file ?

**Comment by felixkiss** [comment]
According to the docs, it would be resources/lang/vendor/uniquewith-validator/ar/messages.php I think

**Comment by ReemAliT** [comment]
@felixkiss  it didn't work .. still stuck on that message

**Comment by ReemAliT** [comment]
@felixkiss  also after adding validation message for arabic language , I still get the same 
 uniquewith-validator::validation.unique_with

Do you have any suggestions ?

**Comment by felixkiss** [comment]
I will look into it this weekend.

**Comment by ReemAliT** [comment]
@felixkiss ok , I'll wait 
thanks

**Comment by felixkiss** [comment]
I created a new Laravel 5 application and used `unique_with`.

I was able to override the default validation message by placing the following file in `resources/lang/vendor/uniquewith-validator/de/validation.php`:

```
<?php

return [
    'unique_with' => 'My custom message: :fields',
];
```

I also set `app.locale` to `de` in the config.

**Comment by ReemAliT** [comment]
@felixkiss  I tried tha same , but still get the same message not the custom one 
it seems like the supported langauges works good but the added one is not 

that's why I thought the adding of Arabic language would fix the issue , but it doesn't .

**Comment by felixkiss** [comment]
What is the output of `dd(Config::get('app.locale'));`?

Also, update to `2.0.3`

**Comment by ReemAliT** [comment]
@felixkiss  "ar" is the output , the Arabic language

sorry , update of what?

**Comment by felixkiss** [comment]
I have created a new repository to show you how to get custom messages to work: https://github.com/felixkiss/uniquewith-validator-custom-message/commits/master

Try it out for yourself:
```
git clone https://github.com/felixkiss/uniquewith-validator-custom-message.git
cd uniquewith-validator-custom-message
composer install
touch storage/database.sqlite
php artisan migrate
php artisan serve
```

Go to `http://localhost:8000` and reload to see it in action.

**Comment by ReemAliT** [comment]
@felixkiss  it works after updating :) 
thank you .. I just updated lately the message syntax to look perfect
