### ISSUE TITLE
validate multiple fields

### ISSUE THREAD

**Issue by isomis** [felixkiss/uniquewith-validator#49]
I want to validate multiple fields, i can do this with this:

$rules['en.title'] =   'required|between:4,65|unique_with:product_translation, en.title = title, '.$id.' = product_id';

But i want to set combination field and the custom name, how does this work? I have the field "locale" thats the combination field and i have als title in place of en.title.

**Comment by felixkiss** [comment]
Just add it to the rule.

```php
$rules['en.title'] = 'required|between:4,65|unique_with:product_translation, locale, en.title = title, '.$id.' = product_id';
```

This will ensure that the combination of `en.title` and `locale` is not yet in the database (but ignores all database rows with a `product_id` of `$id`.

Does this solve it?
