### ISSUE TITLE
Erro to run composer update in Laravel 5.2

### ISSUE THREAD

**Issue by JRAVILES** [felixkiss/uniquewith-validator#54]
Hello, I already used the validator in Laravel 4.2, I'm starting to upgrade to L5.2, did the installation as the documentation ran the 'update composer', and checked that the folder was created on vendors, but when adding the service provider 'Felixkiss \ UniqueWithValidator \ UniqueWithValidatorServiceProvider 'and run composer update again, the following error occurs:

[ReflectionException]           
  Class validator does not exist  
                                  

Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

I also tried adding the service provider as follows:

Felixkiss\UniqueWithValidator\UniqueWithValidatorServiceProvider::class

But the error remains.

Thanks a lot for the help

**Comment by JRAVILES** [comment]
No one?

**Comment by felixkiss** [comment]
The error stays if you remove the `UniqueWithValidatorServiceProvider` altogether? You can try by running `php artisan clear-compiled`.

**Comment by JRAVILES** [comment]
Hi, No. if I remove the UniqueWithValidatorServiceProvider and execute composer update the process finish correctly, I saw that if I add UniqueWithValidatorServiceProvider , before Illuminate \ Validation \ ValidationServiceProvider :: class, the composer update also works perfectly, but it is correct?

**Comment by JRAVILES** [comment]
I did a clean install and added two component that I already use:

         Barryvdh \ DebugBar \ ServiceProvider :: class,
         Krucas \ Notification \ NotificationServiceProvider :: class,

**Comment by JRAVILES** [comment]
AND php artisan clear-compiled

**Comment by felixkiss** [comment]
It looks like the package is not compatible with Laravel 5.2 at the moment, because of changes to the laravel validator.

**Comment by JRAVILES** [comment]
OK, thanks for the help.

**Comment by felixkiss** [comment]
@JRAVILES I have fixed it and it should now be compatible with Laravel 5.2. Please update to the new version `2.0.7`

**Comment by JRAVILES** [comment]
Hi, passed the composer update without problems, I'll do some tests here, thank you very much!

**Comment by maisnamraju** [comment]
This worked with Laravel 5.2, I tested it a while ago and no issues.
