### ISSUE TITLE
Codeception ignoring unique_with?

### ISSUE THREAD

**Issue by ovp87** [felixkiss/uniquewith-validator#56]
For whatever reason i cant for the life of me make my codeception tests respect the unique_with rules. if i post the same data using an http client, i get the expected validation errors, but using codeception it seems to bypass it entirely and just return a database constraint error.

Any suggestions?

UPDATE: it seems this issue is because I'm not including one of the unique values in the POST input, its actually a get variable found in the url.

IE: i'm updating /member/1/hobbies

And want to check that the provided data does not create a duplicate of member 1 and a given hobby.
Is this the intended result?

Still dont get why it works with an http client, and not trough codeception though.

**Comment by felixkiss** [comment]
I don't use codeception. Can you make a example project with a simple route that uses the unique-with validator rule and a codeception test that fails? Otherwise it is really hard to remotely debug this.

Do you include the route parameter in your data array, which you pass into the validator?

**Comment by ovp87** [comment]
I wasn't passing anything into the validator, just using a normal request validator.
Issue was solved by just overwriting the request all() method, like so:

public function all()
{
        $all = Parent::all();
        $all['product_id'] = $this->route()->getParameter('id');
        return $all;
 }

Feels a bit hacky, but it works.

**Comment by felixkiss** [comment]
Feels like the correct and logical approach to me. IMHO not hacky at all.

But why did it work in the browser? That seems weird to me.

**Comment by ovp87** [comment]
> But why did it work in the browser? That seems weird to me.

You and me both, spent about an hour scratching my head, and still haven't figured it out.

**Comment by felixkiss** [comment]
Note: normally in PHP, `parent::` is used all lowercase. http://php.net/manual/en/keyword.parent.php

**Comment by ovp87** [comment]
> Note: normally in PHP, parent:: is used all lowercase

Cheers :+1:
