### ISSUE TITLE
Does not work with 5.2 array validation

### ISSUE THREAD

**Issue by jaysson** [felixkiss/uniquewith-validator#57]
I am trying something like this:

```
'moviePeople.*.person' => 'required|exists:people,id|unique_with:movie_people,moviePeople.*.person = person_id,role',
```

That gives me following error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'moviePeople.0.person' in 'where clause' (SQL: select count(*) as aggregate from `movie_people` where `moviePeople`.`0`.`person` = 1 and `person_id` is null and `role` is null)
```

**Comment by p3ym4n** [comment]
Hi , Any solutions yet?

**Comment by felixkiss** [comment]
@p3ym4n Please help test out #73 and give feedback if possible. It is based on version 3.0.0, so you need to upgrade (Usually only thing necessary is to update the service provider class in your `config/app.php`, which has been renamed)
