### ISSUE TITLE
Multiple keys as Composite Keys

### ISSUE THREAD

**Issue by okao** [felixkiss/uniquewith-validator#59]
I have  a table like this

Schema::create('courseschedueles', function (Blueprint $table) {
            $table->date('date');
            $table->time('starttime');
            $table->time('endtime');
            $table->integer('subject_id')->unsigned()->index();
            $table->foreign('subject_id')->references('id')->on('subjects')->onDelete('cascade');
            $table->integer('hall_id')->unsigned()->index();
            $table->foreign('hall_id')->references('id')->on('halls')->onDelete('cascade');
            $table->timestamps();
            $table->primary(['date', 'starttime', 'endtime', 'hall_id']);
 });

I would like to include 'date', 'starttime', 'endtime', 'hall_id' in my composite key and validate it. A help please

**Comment by xyrintech** [comment]
Any update on this please?

**Comment by felixkiss** [comment]
@xyrintech Are you trying something similar? What does your code look like?

**Comment by xyrintech** [comment]
I have multi tenant architecture. 

Table: 
**tenants**
id 
name

**roles**
id
tenant_id
role_name

I want to have composite keys of tenant_id and role_name as unique in the roles table. 
In order to do this, I am using this package but this seems not to be working.

**Comment by felixkiss** [comment]
What doesn't work? You need to show me some code (how you use the validator), otherwise I can't help you. Any error messages?

**Comment by xyrintech** [comment]
Seems that I missed something before. Please close this.
