### ISSUE TITLE
uniquewith-validator compatibility with softDelete

### ISSUE THREAD

**Issue by rhysp** [felixkiss/uniquewith-validator#6]
With a softDelete-enabled model uniquewith will fail validation if a uniqueness exists even if the entry is in a deleted state (a filled 'deleted_at' field).

**Comment by dadhiramp** [comment]
I am using Laravel 5 and trying to ignore multiple fields validation using the rule 

return [
        'permission_id' => 'required',
        'role_id' => 'required|unique_with:permission_role,permission_id,'.Input::get('role_id').'=role_id,'.Input::get('permission_id').'=permission_id'
    ];

however it turns up saying : 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: update `permission_role` set `permission_id` = 2 where `id` is null)

There is no mention of id, instead i have used custom_id_column as per document, 
for insert case 

return [
		'permission_id' => 'required',
        	'role_id' => 'required|unique_with:permission_role,permission_id'
	    	];

works fine, however having trouble with the ignore case for update.

Thanks

**Comment by felixkiss** [comment]
@dadhiramp 
1) the error doesn't look to be referring to the validator but rather the update statement following a successful validation.

2) specifying more than one ignore column is currently not supported (I think Laravel's PresenceVerifier, which is used in the background, doesn't support multiple ignore columns either).

If you are updating a model, you can use the `id` as the ignore column. Something like:

```php
'role_id' => 'required|unique_with:permission_role, permission_id, ' . $model->id . ' = id',
```

**Comment by dadhiramp** [comment]
Thanks for the prompt response felixkiss ... yes the error is indeed after the validation, seems like i need to add up extra column for it then.

Regards

:+1:

**Comment by ReemAliT** [comment]
the validation is working fine but I get validation error as 
" uniquewith-validator::validation.unique_with"
how can I connect this message to my validation language file ? to get my own error message

**Comment by felixkiss** [comment]
Thanks to #41 the README now documents how to use this package with soft deletes
