### ISSUE TITLE
Validation does not work with database connection name

### ISSUE THREAD

**Issue by Ioquai** [felixkiss/uniquewith-validator#62]
I do have multiple database connections since I am in a multi tenant environment. Therefore I do have to specify the connection name for the validation rule:
`'job_nr'    => 'required|max:255|unique_with:tenant_connection.jobs,name'`

But I always get a `SQLSTATE[42S02]: Base table or view not found` - error. 
It is possible to specify the connection name somehow?

**Comment by LittleBigDev** [comment]
I created PR #66 to fix that. I hope it will be quickly accepted :)
