### ISSUE TITLE
unique_with Validation does not work for arrays

### ISSUE THREAD

**Issue by rishi-ramawat** [felixkiss/uniquewith-validator#64]
I am using `Laravel 5.3` and the following code doesn't work
```
$validator = Validator::make($request->all(), [
    'person.*.email' => 'email|unique_with:users,person.*.email=email',
    'person.*.first_name' => 'required_with:person.*.last_name',
]);
```
It keeps showing and error message saying:
`Unknown column 'person.0.email' in 'where clause'`

**Comment by felixkiss** [comment]
@rishi-ramawat Please help test out #73 and give feedback if possible. It is based on version 3.0.0, so you need to upgrade (Usually only thing necessary is to update the service provider class in your `config/app.php`, which has been renamed)

**Comment by asadghazanfary** [comment]
hi
how can fix this problem:


`'questions.*.question' => 'required|string|unique_with:questions,questions.*.question=question,topic_id,section_id,deleted_at',`

> exception: "Illuminate\Database\QueryException"
file: "D:\laragon\www\fastmotarjem\vendor\laravel\framework\src\Illuminate\Database\Connection.php"
line: 669
message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'questions.0.question' in 'where clause' (SQL: select count(*) as aggregate from `questions` where `questions`.`0`.`question` = ewfew and `topic_id` = 1 and `section_id` = 4)"
trace: [,…]

**Comment by felixkiss** [comment]
@asadghazanfary looks correct, which version of the package and laravel are you using?

**Comment by asadghazanfary** [comment]
"laravel": "6.X"
"uniquewith-validator": "^3.4"
