### ISSUE TITLE
laravel still looking for old service provider

### ISSUE THREAD

**Issue by maisnamraju** [felixkiss/uniquewith-validator#77]
```
Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

                                                                               
  [Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Class 'Felixkiss\UniqueWithValidator\UniqueWithValidatorServiceProvider' no  
  t found                                                                      
                                                                               

Script php artisan optimize handling the post-install-cmd event returned with error code 1
```
I recently upgraded the package from version 2.* to 3 and faced this issue. I have already changed the name of the service provider on the config/app.php file. Very curious as to why it's happening. I am on laravel 5.4 btw, also funny thing is I managed to install it on my local homestead without any issues.

**Comment by Quezler** [comment]
Have you tried `composer dump-autoload`?

**Comment by maisnamraju** [comment]
Hey thanks for the quick answer. I tried it but it didn't work for some reason so i instead delete the files inside the bootstrap folder and it worked. Forgot the name of the exact file.
