### ISSUE TITLE
Unique_with does not work??

### ISSUE THREAD

**Issue by CrixuAMG** [felixkiss/uniquewith-validator#79]
I've added a rule:
` 'name' => 'required|unique_with:templates,organisation_id|min:2'`
And I have data:
`name='test', organisation_id=2`
And when I try to add name='test' with organisation_id 1, it fails.

**Comment by felixkiss** [comment]
I can't reproduce the problem. It behaves correctly for me.

Can you give more specific details about your setup?

**Comment by CrixuAMG** [comment]
The organisation_id is part of the user present in `$request->user()`, it is not being sent as form data.
Using latest stable versions of all packages.

**Comment by CrixuAMG** [comment]
I've changed the rules to be the following:
`$rules = [
            'name' => 'required|unique_with:templates,organisation_id|min:2'
        ];

        $this->merge(['organisation_id' => $this->user()->organisation_id]);

        return $rules;`

But only this is executed in the query:
`select count(*) as aggregate from `templates` where `name` = 'test';`

**Comment by felixkiss** [comment]
Are you using a `FormRequest` object? What is this `merge` method you are calling?

**Comment by CrixuAMG** [comment]
I've created a request class using `php artisan make:request RequestName`.
This creates a class that extends the FormRequest class by default, and has been some time in Laravel ;)
The `merge` method I'm using is the exact same as having `Request $request` as a parameter in a method, and then calling `$request->merge(['some data' => 'some value']);`

**Comment by felixkiss** [comment]
Still having issues or can this issue be closed? It worked in [my example](https://github.com/felixkiss/uniquewith-validator/issues/79#issuecomment-321592880)

**Comment by CrixuAMG** [comment]
The issue is still here. 
When doing what I said in my original post:
```
I've added a rule:
'name' => 'required|unique_with:templates,organisation_id|min:2'
And I have data:
name='test', organisation_id=2
And when I try to add name='test' with organisation_id 1, it fails.
```

Still fails.

**Comment by tonnevillec** [comment]
Hi,
I have the same problem but in reverse.
I can rename an organization while another exists and already has the name passed as a parameter.

**Comment by felixkiss** [comment]
@tonnevillec please open a new issue with more details and code that shows how you use the library so I can reproduce or advise

**Comment by felixkiss** [comment]
@tonnevillec 

- What version of Laravel and uniquewith-validator do you use?
- Please post output of this `php artisan tinker` snippet:
```php
DB::table('client')->insert(['name' => 'foo-bar', 'owner_id' => 1]);
Validator::make(['name' => 'foo-bar', 'owner_id' => 1], ['name' => 'unique_with:client,owner_id'])->errors();
Validator::make(['name' => 'foo-bar', 'owner_id' => 2], ['name' => 'unique_with:client,owner_id'])->errors();
```

**Comment by tonnevillec** [comment]
Laravel 5.2.45
uniquewith 3.0.0

`>>> DB::table('client')->insert(['name'=>'foo-bar', 'owner_id'=>2544]);
=> true
>>> Validator::make(['name'=>'foo-bar', 'owner_id'=>2544], ['name'=>'unique_with:client,owner_id'])->errors();
=> Illuminate\Support\MessageBag {#945}
>>> Validator::make(['name'=>'essai', 'owner_id'=>2544], ['name'=>'unique_with:client,owner_id'])->errors();
=> Illuminate\Support\MessageBag {#946}`

I don't know if it can help. The second test with 'essai' should normaly return an error...

**Comment by CrixuAMG** [comment]
@tonnevillec I would expect `foo-bar` to be the one causing an error, since you specify the name should be unique in combination with the owner id. 
Can you dump what's inside the MessageBag?

**Comment by tonnevillec** [comment]
... in the messageBag i have the error as expected.
But in my api it doesn't work.

`
        $this->validate($request, [
            'name' => 'required|unique_with:client,owner_id|min:2'
        ]);
`

**Comment by tonnevillec** [comment]
sorry i found my mistake and it does not depend on uniquewith

**Comment by CrixuAMG** [comment]
Can you elaborate on what went wrong?

**Comment by tonnevillec** [comment]
Just an error in the call of my owner_id so when I wanted to test the uniqueness of the name for the owner I always had a return "ok" because the couple name / owner did not necessarily exist.

**Comment by CrixuAMG** [comment]
Ok, thanks for the information 👍
