### ISSUE TITLE
What Class to Use

### ISSUE THREAD

**Issue by dashawk** [felixkiss/uniquewith-validator#80]
Hi,

I am trying to validate multiple records before inserting it all.

```php

// Currently using the facade validator
use Illuminate\Support\Facades\Validator;

$data = [
    'items' => [
        ['bID' => 1, 'slot' => 2],
        ['bID' => 2, 'slot' => 2]
    ]
];

// bID and slot are unique.

$v = Validator::make($data, [
    'items.*.bID' => 'required|unique_with:samples, slot'
]);

if ($v->fails()) {
    return response()->json([$v->errors()]);
}

return response()->json(['success']);
```

The `unique_with` doesn't seem to work for me.

When I run it, I get an error:
![image](https://user-images.githubusercontent.com/1437205/29205775-6421a9f8-7eb1-11e7-9f8b-c363f2a70646.png)

Am I using the wrong validator?

**Comment by felixkiss** [comment]
When using the array validation rule, you need to specify the name in the database explicitly like so:

```
$v = Validator::make($data, [
    'items.*.bID' => 'required|unique_with:samples,items.*.bID = bID,slot'
]);
```

**Comment by dashawk** [comment]
Hi, I have tried your suggestion and it works if the list of items to be inserted are unique in one go, but if the items has some identical row in one go, I got this error.
![image](https://user-images.githubusercontent.com/1437205/29342223-2d6490ac-825c-11e7-9123-651c50cf8dc6.png)

```php
// The items here has no identical item
$data = [
    'items' => [
        ['bID' => 1, 'slot' => 2],
        ['bID' => 2, 'slot' => 2]
    ]
];

// Here, the two items are identical. this is where
// I want to handle the error but I keep getting the
// constraint violation error popping out.
$data = [
    'items' => [
        ['bID' => 1, 'slot' => 2],
        ['bID' => 1, 'slot' => 2]
    ]
];
```

**Comment by felixkiss** [comment]
The validator does not change anything in your database, so it works as intended.

If no two items with the same `bID`/`slot` combination are allowed, you have to consolidate your input. You could eliminate duplicates or write a custom validator that asserts that there are only unique items in your input (and return an appropriate error message if there are duplicates)

This could look something like this:
```php
$rules = [
    'items.*' => 'no-duplicates',
    'items.*.bID' => 'required|unique_with:samples, items.*.bID = bID, slot',
];
```

Where `no-duplicates` is your [custom validator rule](https://laravel.com/docs/5.4/validation#custom-validation-rules).

**Comment by dashawk** [comment]
I see, ok I will get back to you after I created my custom rule.

I will just leave this open for now.

Thanks.

**Comment by felixkiss** [comment]
Closed because of inactivity
