### ISSUE TITLE
`<field1>` on different place

### ISSUE THREAD

**Issue by nickreynke** [felixkiss/uniquewith-validator#81]
I'm currently developing an API and the keys, of the incoming JSON data that have to be validated, do not match the actual database column names.

Incoming JSON for a POST request may look like this:

```json
{
  "data": {
    "attributes": {
      "date": "2017-08-25"
    },
    "relationships": {
      "employee": {
        "set": "202"
      }
    }
  }
}
```

As the documentation describes I would check if the column `date` is unique with the column `employee_id` but I actually would need to check if `data.attributes.date` is unique with `employee_id`.

So ...

`'<field1>' => 'unique_with:<table>,<field2>[,<field3>,...,<ignore_rowid>]',`

... would become ...

`'data.attributes.date' => 'unique_with:<table>,employee_id',`

Is there any chance that the `unique_with` validator could look like this: (?)

`'<custom_field_name>' => 'unique_with:<table>,<field1>,<field2>[,<field3>,...,<ignore_rowid>]',`

Stacktrace:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'data.attributes.date' in 'where clause' (SQL: select count(*) as aggregate from `employees` where `data`.`attributes`.`date` = 2017-08-25)
```

**Comment by felixkiss** [comment]
You can specify a custom name for the date as in:

```php
$rules = [
    'data.attributes.date' => 'unique_with: employees, data.attributes.date = employed_at, relationships.employee.set = employee_id',
];

**Comment by nickreynke** [comment]
Thanks that worked. :)
