### ISSUE TITLE
Unique, where

### ISSUE THREAD

**Issue by nickreynke** [felixkiss/uniquewith-validator#82]
I'm trying to achieve the following validation:

```php
'data.attributes.mail-address' => [
    'email',
    'max:255',
    sprintf(
        'unique_with:employees,data.attributes.mail-address = mail_address,%s = customer_id',
        $user->getAttribute('customer_id')
    ),
],
```

A mail address should be unique to the customer the employee is assigned to. Is this somehow possible to achieve?

**Comment by felixkiss** [comment]
Very old issue. Sorry for not responding. I assume you don't need more help. If you need, feel free to reopen.
