### ISSUE TITLE
Wildcard access not working on numeric arrays

### ISSUE THREAD

**Issue by bluetrickpt** [felixkiss/uniquewith-validator#84]
The title may be misleading, and I will try to explain this with an example. 
This discussions started in pull #73 (see last comments). I have added @felixkiss's suggestion, but it didn't work. 

Assume you have:
`$data = [
    "user_id": [
        1,
        3
    ],
   "post_id": 1
];`
`$rules= [ 'user_id.*' => 'unique_with:post_user, user_id.* = user_id, post_id' ];`
`$validator = Validator::make($data, $rules);`

The error that I get is:
> "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_id.0' in 'where clause' (SQL: select count(*) as aggregate from `post_user` where `user_id`.`0` = 1 and `post_id` = 1)"

So, it seems to me that the wildcard in `user_id.* = user_id` is not being processed when the array is non associative.
Please let me know if this is simply me doing something wrong, or is indeed an issue.
Thank you

**Comment by felixkiss** [comment]
Very old issue. Sorry for not responding. I assume you don't need more help. If you need, feel free to reopen.
