### ISSUE TITLE
Unique composite Key and ignore current keys on update

### ISSUE THREAD

**Issue by yelnyaface** [felixkiss/uniquewith-validator#85]
I am not able to make unique_with work for UPDATE request, where I need to ignore the current existing foreign keys for the rows, how can I do that?

**Comment by felixkiss** [comment]
When updating a record with say id `123`, you can just add the following to the rule: `,ignore:123` and it will ignore that ID when searching for currently existing foreign keys.

**Comment by yelnyaface** [comment]
I see, thanks for the reply, I currently have a pivot table with `user_id` and a `res_id` and no primary ID key, and this is how my `$rules` currently look like:

>
>$rules = [
>
>   'user_id'              => 'required|integer|unique_with:user_visit_count,res_id,ignore:' . $user,
>   'res_id'                => 'required|integer',
>
>......
>
>];

the validation error message is showing:

`This combination of user id, res id, ignore:{"id":1, cardnumber id:2, name:" ....... } already exists.`

In the `UPDATE` request, if the `user_id` and `res_id` is not changed, but the extra pivot table attributes are changed, then it will show the validation error message like above, any way to ignore the  `user_id` and `res_id` of current existing row?

seems the `unique_with` validation requires the` id` column which the pivot table dont have

**Comment by felixkiss** [comment]
Only one ignore column is supported, since this library uses Laravel's `PresenceVerifierInterface`. But you could specify the name like this:

```
'user_id' => 'required|integer|unique_with:user_visit_count,res_id, ignore:' . $user->id . ' = user_id',
```

In your case this won't help, but I would suggest adding a auto-incrementing `id` to the table and using that for the ignore.

**Comment by MicroDreamIT** [comment]
anyway I am trying to use this for unique name, but its not working. Any help will be appreciated, 

```
'required|integer|unique_with:user_visit_count,res_id,ignore:' . $user,
```

**Comment by felixkiss** [comment]
Old issue. Sorry for not responding. I assume you don't need more help. If you need, feel free to reopen.
