### ISSUE TITLE
Unique with date fields

### ISSUE THREAD

**Issue by HumbertoSilveira** [felixkiss/uniquewith-validator#86]
I want to have uniques name and date of birth on table. 
I did this:
`$rules = [
            'nome' => 'required|unique_with:pessoa, data_nascimento',
            'data_nascimento' => 'required|date_format:d/m/Y|before:today'
]`
The validation pass even if exists another row in database with the same name and date of birth. I think it pass because of the format of my date, if that is the case how can I validate this?

**Comment by felixkiss** [comment]
Is `data_nascimento` a date or datetime field? is it converted to a `DateTime` object or are you just working with strings?

**Comment by HumbertoSilveira** [comment]
It is a date field, I have a mask on my input to set the format to d/m/Y and a mutator to save the value correctly on the database format (Y-m-d)

**Comment by HumbertoSilveira** [comment]
I had tested with other fields and It works, It doesn't work only with data_nascimento field

**Comment by felixkiss** [comment]
I'm guessing the validation takes place before the values are set on the model (therefore also before the mutator runs). You have to do the transformation to `Y-m-d` on the data before it gets validated.

**Comment by HumbertoSilveira** [comment]
Ok, I'm gonna change my code and adapt to see If it works. Thanks
