### ISSUE TITLE
How to manage unique_with combination of three columns but to allow two

### ISSUE THREAD

**Issue by shone83** [felixkiss/uniquewith-validator#88]
I manage to set not to allow these three combination: name, last_name and telephone. The problem is when I want to enter same name and last_name but without telephone (when telephone is empty or null), I need to allow that but in this code it doesn't:

```
'name'  => 'unique_with:add_members, last_name, telephone_1',
```
When I make one column unique I use nullable function but here it doesn't work...

**Comment by felixkiss** [comment]
I think your options are:

- If `telephone` is not present in your data array at all, you can declare the unique_with rule for the `telephone` attribute like `'telephone_1' => 'unique_with: add_members, name, last_name'`
- If `telephone` is empty or null, you can check and either remove it from the data array or only add the rule if it is not empty like `if (empty($data['telephone_1']) { unset($data['telephone_1']); }`

**Comment by shone83** [comment]
I tried like that:
```
'telephone_1'   => 'unique_with:add_members, name, last_name',
```
and result is same: **This combination of telephone 1, name, last name already exists.**

The second answer I didn't understand, where to use if statement, in controller or request? This is my full function now:

```
public function rules()
{
    return [
        'name'          => 'required',
        'last_name'     => 'required',
        'social_number' => 'nullable|unique:add_members',
        'telephone_1'   => 'unique_with:add_members, name, last_name',
        'street'        => 'unique_with:add_members, name, last_name, number',
    ];
}
```

As you can see, I have one more unique_with function in same table, with same problem :)
