### ISSUE TITLE
Laravel 5.4 : doesn't work on updating !

### ISSUE THREAD

**Issue by AEK-BKF** [felixkiss/uniquewith-validator#93]
Hi,
I have an issue when I'm trying to update ! ( Create works fine ) 

Here my code :
```
public static function editRules($id) {
      return array(                         
          'title' => 'required|string|max:255|unique_with:survey_questions,survey_id,'.$id, 
          'order' =>'integer'                      
     );
} 
```

Thanks.

**Comment by felixkiss** [comment]
Does `$id` refer a DB column named `id`? If not, you have to specify the DB column name (In your case probably something like `...,survey_id,'.$id.' = survey_id',`)

**Comment by AEK-BKF** [comment]
Thanks for quick reply !
No, it's the auto-increment ID of survey_questions

**Comment by felixkiss** [comment]
Ok, so the auto increment ID is named `id` in the DB? Just to be sure, try it like this:
```
'title' => 'required|string|max:255|unique_with:survey_questions,survey_id,ignore:'.$id,
```

**Comment by AEK-BKF** [comment]
Sorry same issue :/

**Comment by AEK-BKF** [comment]
Sorry I found the mistake ! it's the question_id value !! I was fixed :)))))))

Thank you so much
